service: eb-sqs-demo
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: events:PutEvents
          Resource: !GetAtt EventBus.Arn

custom:
  apiGatewayServiceProxies:
    - eventbridge:
        path: /eventbridge
        method: post
        source: "fuel-app"
        detailType: "user-signup"
        eventBusName: { Ref: EventBus }
        cors: true
        private: false

functions:
  processEventLambda:
    handler: functions/processEvent.handler
    events:
      - sqs:
          arn: !GetAtt TargetSQS.Arn
          batchSize: 10
          functionResponseType: "ReportBatchItemFailures"
  putEventsLambda:
    handler: functions/putEvents.handler
    environment:
      EventBusName: !Ref EventBus
    events:
      - http:
          path: /generate
          method: post

resources:
  - ${file(resources.yml)}

plugins:
  - serverless-apigateway-service-proxy
